22 kvíz oldal elkezdése
matyas94/Rajongoi9A-D pull request #39
Opened 2024-03-25 20:10 UTC by szerimartin

tökéletesen működik még a responsivitással lehetnek problémák amugy jó és már csak a kérdések kellenek bele

2024-03-26 07:02 UTC, matyas94 approved these changes
Leave a comment

2024-03-26 07:18 UTC, OlahBalazs1 approved these changes

2024-04-07 08:26 UTC, OlahBalazs1 requested changes
bruh nem indul el

2024-04-07 09:02 UTC, OlahBalazs1 approved these changes
mostmár jó

2024-04-07 09:54 UTC, merged